services:
  frontend:
    build: 
      context: .
      dockerfile: ./homeless-shelter-availability-web/Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY:-}
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./homeless-shelter-availability-api/Dockerfile
    container_name: backend
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/HSADB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ZkY6tG5lp

  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ZkY6tG5lp
      POSTGRES_DB: HSADB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d HSADB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
