sonar.projectKey=homeless-shelter-availability
sonar.projectName=Homeless Shelter Availability
sonar.sourceEncoding=UTF-8

sonar.sources=homeless-shelter-availability-api/src/main/java,homeless-shelter-availability-web/dist/assets
sonar.tests=homeless-shelter-availability-api/src/test/java,homeless-shelter-availability-web/tests

sonar.java.binaries=homeless-shelter-availability-api/target/classes
sonar.junit.reportPaths=homeless-shelter-availability-api/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=homeless-shelter-availability-api/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=homeless-shelter-availability-web/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/.scannerwork/**,homeless-shelter-availability-web/dist/config.js
